import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { CANDIDATE_C, PHASE_2_CANDIDATES } from '@/lib/casino/candidates';

/**
 * **Pinned to the Phase 2 family on purpose.**
 *
 * This script is the record of the analysis that produced the 2026-08-11
 * rulings, and it reads `CANDIDATE_C` rather than `RECOMMENDED` so that later
 * changes to the recommendation cannot silently rewrite the evidence those
 * rulings were made on. Phase 3 has its own script.
 */
const CANDIDATES = PHASE_2_CANDIDATES;
const RECOMMENDED = CANDIDATE_C;
import {
  INFINITE_DECK_NATURAL,
  SINGLE_DECK_NATURAL,
  playSingleDeck,
  solveInfiniteDeck,
} from '@/lib/casino/blackjack-model';
import { analyse, auditPaytable } from '@/lib/casino/slots-model';
import { CATALOG_SIZE } from '@/lib/counter/catalog';
import { standardRewardTable } from '@/lib/counter/rewards';
import { PROVISIONAL_ECONOMY } from '@/lib/counter/tokens';
import {
  CADENCE,
  CASINO_ARCHETYPES,
  type CasinoArchetype,
  type CasinoPolicy,
  SLOT_SHARE,
  blackjackGame,
  defaultRoster,
  slotsGame,
  uniformRoster,
} from '@/lib/economy/casino-scenario';
import {
  SCORED_WEEKS,
  checkRanges,
  generator,
  salvageFor,
  simulate,
  type SimulationResult,
} from '@/lib/economy/simulate';

/**
 * The casino readiness analysis — `NEXT PHASE §B`–`§D`.
 *
 *   npx tsx scripts/casino-analysis.ts
 *
 * It prints, and writes one evidence file. **It changes no product value, opens
 * no door and approves nothing.**
 */

const SEASONS = 50;
const MANAGERS = 10;
const SEED = 20260804;
const CASINO_SEED = 20260811;
const BLACKJACK_HANDS = 20_000_000;
const BLACKJACK_WAGER = 40;
const SLOTS_WAGER = 10;

const out: string[] = [];
const say = (line = ''): void => {
  out.push(line);
  console.log(line);
};

const pct = (x: number, dp = 2): string => `${(x * 100).toFixed(dp)}%`;

function percentile(values: readonly number[], q: number): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const pos = (sorted.length - 1) * q;
  const lo = Math.floor(pos);
  const hi = Math.ceil(pos);
  const a = sorted[lo] ?? 0;
  const b = sorted[hi] ?? 0;
  return a + (b - a) * (pos - lo);
}

/** Gini over non-negative values. `0` is perfect equality. */
function gini(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const n = sorted.length;
  const total = sorted.reduce((a, b) => a + b, 0);
  if (n === 0 || total === 0) return 0;
  let weighted = 0;
  for (let i = 0; i < n; i += 1) weighted += (i + 1) * (sorted[i] ?? 0);
  return (2 * weighted) / (n * total) - (n + 1) / n;
}

/* ------------------------------------------------------------ blackjack -- */

say('# Casino analysis — blackjack, slots, and a full-league economy run');
say();
say(`Generated by \`npx tsx scripts/casino-analysis.ts\`. Nothing here is approved.`);
say();
say('## 1. Blackjack, under the approved rules (R2, R4)');
say();

const exact = solveInfiniteDeck();
const bjRandom = generator(4242);
const sampled = playSingleDeck(BLACKJACK_HANDS, bjRandom, exact.hitTable);

say('Rules modelled: hit · stand · natural · bust · dealer draw · push · dealer stands on all 17 ·');
say('natural pays 3:2 · no split, double, surrender or insurance · one fresh 52-card deck per hand.');
say();
say('| Model | House edge | EV per unit | Method |');
say('|---|---|---|---|');
say(
  `| Infinite deck (continuous shuffle) | **${exact.houseEdgePercent.toFixed(4)}%** | ${exact.ev.toFixed(6)} | exact enumeration, no sampling |`,
);
say(
  `| **Single deck — the shipped model** | **${sampled.houseEdgePercent.toFixed(4)}%** | ${sampled.ev.toFixed(6)} | ${(BLACKJACK_HANDS / 1e6).toFixed(0)}M hands, σ/√n = ${sampled.standardError.toFixed(6)} |`,
);
say();
say(
  `The single-deck figure is the one to use. Its 4σ band is ±${(4 * sampled.standardError * 100).toFixed(4)} percentage points, ` +
    `so the two models differ by ${Math.abs(sampled.houseEdgePercent - exact.houseEdgePercent).toFixed(4)} points — ` +
    `${Math.abs(sampled.ev - exact.ev) > 4 * sampled.standardError ? 'a real difference, not noise' : 'inside the noise'}.`,
);
say();
say(
  `Natural frequency is the mechanism: a single deck deals one ${pct(SINGLE_DECK_NATURAL, 3)} of the time against ` +
    `${pct(INFINITE_DECK_NATURAL, 3)} with infinite cards, because an ace you hold is one of four rather than one of thirteen.`,
);
say();
say('### Outcome distribution, per hand (single deck, measured)');
say();
say('| Outcome | Frequency | Pays |');
say('|---|---|---|');
say(`| Natural blackjack | ${pct(sampled.outcomes.natural, 3)} | +1.5× |`);
say(`| Win | ${pct(sampled.outcomes.win)} | +1× |`);
say(`| Push | ${pct(sampled.outcomes.push)} | 0 |`);
say(`| Loss (outdrawn) | ${pct(sampled.outcomes.loss)} | −1× |`);
say(`| Loss (bust) | ${pct(sampled.outcomes.bust)} | −1× |`);
say();
say(`Standard deviation per hand: **${sampled.standardDeviation.toFixed(4)}** units of the wager.`);
say();
say('### Expected token value per hand, at the approved buttons (R3)');
say();
say('| Wager | Expected loss per hand | Natural pays | 100 hands | 1,000 hands |');
say('|---|---|---|---|---|');
for (const wager of [20, 40, 80]) {
  const perHand = -sampled.ev * wager;
  say(
    `| ${String(wager)} | ${perHand.toFixed(3)} tokens | ${String(wager + wager * 1.5)} | −${(perHand * 100).toFixed(0)} ± ${(4 * sampled.standardDeviation * wager * Math.sqrt(100)).toFixed(0)} | −${(perHand * 1000).toFixed(0)} ± ${(4 * sampled.standardDeviation * wager * Math.sqrt(1000)).toFixed(0)} |`,
  );
}
say();
say(
  'All three buttons are even, so a 3:2 natural is always a whole number of tokens — 30, 60 and 120 respectively. ' +
    'That is R4 and R3 agreeing, and it is the reason the denominations cannot be odd.',
);
say();

/* ---------------------------------------------------------------- slots -- */

say('## 2. Slots candidates (R5, R6, R7)');
say();

for (const table of CANDIDATES) {
  const a = analyse(table);
  const problems = auditPaytable(table);
  say(`### ${table.id}`);
  say();
  say(`*${table.summary}*`);
  say();
  say(
    `**RTP ${pct(a.rtp)}** · hit rate ${pct(a.hitRate)} (of which money-back ${pct(a.moneyBackRate)}, ` +
      `true win ${pct(a.winRate)}) · loss ${pct(a.lossRate)} · volatility ${a.volatility.toFixed(3)}`,
  );
  say();
  say(`Top prize: ${a.topPrize.label} at ${String(a.topPrize.multiplier)}×, probability ${pct(a.topPrize.probability, 4)} (1 in ${Math.round(1 / a.topPrize.probability).toLocaleString('en-US')} spins).`);
  say();
  say('| Combination | Probability | Pays | Contribution to RTP |');
  say('|---|---|---|---|');
  for (const line of a.lines) {
    say(`| ${line.label} | ${pct(line.probability, 4)} | ${String(line.multiplier)}× | ${pct(line.returned, 3)} |`);
  }
  say(`| *nothing* | ${pct(a.lossRate, 4)} | 0 | — |`);
  say();
  say('| Button | Expected loss per spin | Max single payout | Payout ≥ stake |');
  say('|---|---|---|---|');
  for (const wager of table.wagers) {
    say(
      `| ${String(wager)} | ${(a.expectedLossByWager.get(wager) ?? 0).toFixed(3)} tokens | ` +
        `${String(a.maxPayoutByWager.get(wager) ?? 0)}${(a.maxPayoutByWager.get(wager) ?? 0) > table.capTokens ? ` ⚠ over the ${String(table.capTokens)} cap` : ''} | ${pct(a.hitRate)} |`,
    );
  }
  say();
  if (problems.length === 0) {
    say('**Coherence audit: clean.**');
  } else {
    say('**Coherence audit: REFUSED.**');
    for (const problem of problems) say(`- ${problem}`);
  }
  say();
}

/* ------------------------------------------------------------- baseline -- */

say('## 3. Baseline preservation');
say();

const table = standardRewardTable();
const base = {
  economy: PROVISIONAL_ECONOMY,
  salvage: salvageFor(PROVISIONAL_ECONOMY.standardBoxPriceTokens),
  grantsPerSeason: 2,
  table,
  seasons: SEASONS,
  managers: MANAGERS,
  weeks: SCORED_WEEKS,
  policy: 'specified' as const,
  seed: SEED,
  catalogSize: CATALOG_SIZE,
};

/*
 * The per-manager fingerprint that proves the casino draws from its own
 * generator lives in `lib/casino/casino.test.ts`, not here. A script that
 * printed it would be a report nobody reads asserting a property nobody runs;
 * the test goes red.
 */
const baseline = simulate(base);
const baselineChecks = checkRanges(baseline);

say('The approved gate, run with no casino policy supplied:');
say();
say('| Check | Range | Measured | |');
say('|---|---|---|---|');
for (const check of baselineChecks) {
  say(
    `| ${check.name} | ${check.range} | ${check.measured} | ${!check.gating ? 'reported' : check.withinRange ? '✓' : '✗'} |`,
  );
}
say();
say(
  `Gate: **${baselineChecks.filter((c) => c.gating).every((c) => c.withinRange) ? 'PASS' : 'FAIL'}** — ` +
    'identical to the figures already recorded in `docs/ECONOMY_SIMULATION.md`.',
);
say();

/* ------------------------------------------------------------- scenarios -- */

function policyFor(archetypes: readonly CasinoArchetype[]): CasinoPolicy {
  return {
    archetypes,
    slots: slotsGame(RECOMMENDED, SLOTS_WAGER),
    blackjack: blackjackGame(sampled.outcomes, BLACKJACK_WAGER),
    slotShare: SLOT_SHARE,
    reserveTokens: 0,
    seed: CASINO_SEED,
  };
}

say('## 4. Full-season casino simulation');
say();
say(
  `${String(SEASONS)} seasons · ${String(MANAGERS)} managers · ${String(SCORED_WEEKS)} scored weeks · ` +
    `seed ${String(SEED)} / casino seed ${String(CASINO_SEED)} · box ${String(PROVISIONAL_ECONOMY.standardBoxPriceTokens)} tokens.`,
);
say();
say(
  `Games: **${RECOMMENDED.id}** at the ${String(SLOTS_WAGER)}-token button, blackjack at ${String(BLACKJACK_WAGER)}. ` +
    `${pct(SLOT_SHARE, 0)} of plays are spins. Managers gamble **before** buying, and hold back nothing.`,
);
say();
say('| Archetype | Plays/week | Boxes/season (median) | p10 | p90 | Unique items | Wagered | Returned | Net |');
say('|---|---|---|---|---|---|---|---|---|');

interface Row {
  readonly archetype: string;
  readonly boxes: number;
  readonly p10: number;
  readonly p90: number;
  readonly owned: number;
  readonly net: number;
  readonly balances: readonly number[];
  readonly result: SimulationResult;
}

const rows: Row[] = [];

for (const archetype of CASINO_ARCHETYPES) {
  const result =
    archetype === 'none'
      ? baseline
      : simulate({ ...base, casino: policyFor(uniformRoster(MANAGERS, archetype)) });

  const perSeason = result.managers.flatMap((m) => m.boxesPerSeason);
  const wagered = result.managers.reduce((n, m) => n + m.casinoWagered, 0);
  const returned = result.managers.reduce((n, m) => n + m.casinoReturned, 0);
  const owned = result.managers.reduce((n, m) => n + m.owned, 0) / MANAGERS;

  rows.push({
    archetype,
    boxes: percentile(perSeason, 0.5),
    p10: percentile(perSeason, 0.1),
    p90: percentile(perSeason, 0.9),
    owned,
    net: returned - wagered,
    balances: result.managers.map((m) => m.endingBalance),
    result,
  });

  say(
    `| ${archetype} | ${String(CADENCE[archetype])} | **${percentile(perSeason, 0.5).toFixed(1)}** | ` +
      `${percentile(perSeason, 0.1).toFixed(1)} | ${percentile(perSeason, 0.9).toFixed(1)} | ` +
      `${owned.toFixed(1)} / ${String(CATALOG_SIZE)} | ` +
      `${wagered.toLocaleString('en-US')} | ${returned.toLocaleString('en-US')} | ` +
      `${returned - wagered >= 0 ? '+' : ''}${(returned - wagered).toLocaleString('en-US')} |`,
  );
}

say();
say('### The gate, re-run under each archetype');
say();
say('| Archetype | Boxes/manager/season (6–12) | Legendary mass | Sampled rate | Gate |');
say('|---|---|---|---|---|');
for (const row of rows) {
  const checks = checkRanges(row.result);
  const boxes = checks.find((c) => c.name.startsWith('Boxes'));
  const mass = checks.find((c) => c.name.startsWith('Legendary mass'));
  const rate = checks.find((c) => c.name.startsWith('Legendary rate'));
  const pass = checks.filter((c) => c.gating).every((c) => c.withinRange);
  say(
    `| ${row.archetype} | ${boxes?.measured ?? '—'} ${boxes?.withinRange ? '✓' : '✗'} | ` +
      `${mass?.measured ?? '—'} ${mass?.withinRange ? '✓' : '✗'} | ${rate?.measured ?? '—'} ${rate?.withinRange ? '✓' : '✗'} | ` +
      `**${pass ? 'PASS' : 'FAIL'}** |`,
  );
}
say();

/* ---------------------------------------------------------------- tails -- */

say('## 5. Tail risk and concentration');
say();
say('A median cannot see a casino. These are the statistics that can.');
say();
say('| Archetype | Ending balance p10 | median | p90 | Gini | Top manager share |');
say('|---|---|---|---|---|---|');
for (const row of rows) {
  const total = row.balances.reduce((a, b) => a + b, 0);
  const top = Math.max(...row.balances);
  say(
    `| ${row.archetype} | ${percentile(row.balances, 0.1).toFixed(0)} | ${percentile(row.balances, 0.5).toFixed(0)} | ` +
      `${percentile(row.balances, 0.9).toFixed(0)} | ${gini(row.balances).toFixed(3)} | ` +
      `${total === 0 ? '—' : pct(top / total, 1)} |`,
  );
}
say();

const mixed = simulate({ ...base, casino: policyFor(defaultRoster(MANAGERS)) });
say('### The mixed league — one heavy, one regular, and the rest spread');
say();
say(
  'The heavy gambler is placed on **manager 0, who is also the best fantasy manager**, because that is the ' +
    'pairing in which compounding would be loudest.',
);
say();
say('| Seat | Football | Casino | Boxes/season | Unique items | Wagered | Net casino | Ending balance |');
say('|---|---|---|---|---|---|---|---|');
for (const m of mixed.managers) {
  const boxes = m.boxesPerSeason.reduce((a, b) => a + b, 0) / SEASONS;
  say(
    `| | ${m.profile} | ${m.casinoArchetype} | ${boxes.toFixed(1)} | ${String(m.owned)} / ${String(CATALOG_SIZE)} | ` +
      `${m.casinoWagered.toLocaleString('en-US')} | ${m.casinoReturned - m.casinoWagered >= 0 ? '+' : ''}${(m.casinoReturned - m.casinoWagered).toLocaleString('en-US')} | ` +
      `${m.endingBalance.toLocaleString('en-US')} |`,
  );
}
say();

const mixedChecks = checkRanges(mixed);
say('| Check | Range | Measured | |');
say('|---|---|---|---|');
for (const check of mixedChecks) {
  say(
    `| ${check.name} | ${check.range} | ${check.measured} | ${!check.gating ? 'reported' : check.withinRange ? '✓' : '✗'} |`,
  );
}
say();
say(
  `Mixed-league gate: **${mixedChecks.filter((c) => c.gating).every((c) => c.withinRange) ? 'PASS' : 'FAIL'}**.`,
);
say();

/* ------------------------------------------------------------ sink size -- */

const heavy = rows.find((r) => r.archetype === 'heavy');
const leagueWideSink = mixed.managers.reduce((n, m) => n + (m.casinoWagered - m.casinoReturned), 0);
say('## 6. League-wide sink');
say();
say(
  `Across ${String(SEASONS)} seasons the mixed league fed the casino ` +
    `**${leagueWideSink.toLocaleString('en-US')} tokens** net — ` +
    `${(leagueWideSink / SEASONS).toFixed(0)} a season, or ` +
    `${(leagueWideSink / SEASONS / PROVISIONAL_ECONOMY.standardBoxPriceTokens).toFixed(1)} boxes' worth ` +
    'of purchasing power removed from the league each year.',
);
if (heavy !== undefined) {
  const perManagerPerSeason = -heavy.net / MANAGERS / SEASONS;
  say();
  say(
    `A manager playing at the **heavy** cadence for a whole season loses about ` +
      `**${perManagerPerSeason.toFixed(0)} tokens a year** — ${(perManagerPerSeason / PROVISIONAL_ECONOMY.standardBoxPriceTokens).toFixed(1)} boxes.`,
  );
}
say();

/* ------------------------------------------------------------ season one -- */

say('## 7. Season one, which is the only season that exists');
say();
say(
  'The fifty-season run above **saturates**: every manager owns all twenty-four items by season two, ' +
    'so it cannot see damage to collection progression — the thing R8 actually cares about. ' +
    'This block runs a single season, which is the horizon the league will really be judged on.',
);
say();
say('| Archetype | Boxes in season 1 (median) | p10 | p90 | Unique items (median) | p10 | Net casino |');
say('|---|---|---|---|---|---|---|');

const seasonOne = { ...base, seasons: 1 };
for (const archetype of CASINO_ARCHETYPES) {
  const result =
    archetype === 'none'
      ? simulate(seasonOne)
      : simulate({ ...seasonOne, casino: policyFor(uniformRoster(MANAGERS, archetype)) });

  const boxes = result.managers.flatMap((m) => m.boxesPerSeason);
  const owned = result.managers.map((m) => m.owned);
  const net = result.managers.reduce((n, m) => n + m.casinoReturned - m.casinoWagered, 0);

  say(
    `| ${archetype} | **${percentile(boxes, 0.5).toFixed(1)}** | ${percentile(boxes, 0.1).toFixed(1)} | ` +
      `${percentile(boxes, 0.9).toFixed(1)} | **${percentile(owned, 0.5).toFixed(1)}** / ${String(CATALOG_SIZE)} | ` +
      `${percentile(owned, 0.1).toFixed(1)} | ${net >= 0 ? '+' : ''}${net.toLocaleString('en-US')} |`,
  );
}
say();

/* --------------------------------------------------------- the mitigation -- */

say('## 8. The reserve, as a sensitivity');
say();
say(
  'Every run above holds back **nothing** — a manager gambles whatever is on the tab. That is the ' +
    'conservative assumption and it is not a prediction. This block repeats the heavy archetype with the ' +
    'manager reserving the price of one box before playing, which is what a manager who is collecting ' +
    'actually does.',
);
say();
say('| Reserve | Boxes/season (median) | p10 | p90 | Unique items after season 1 | Gate |');
say('|---|---|---|---|---|---|');

for (const reserve of [0, PROVISIONAL_ECONOMY.standardBoxPriceTokens]) {
  const policy: CasinoPolicy = { ...policyFor(uniformRoster(MANAGERS, 'heavy')), reserveTokens: reserve };
  const long = simulate({ ...base, casino: policy });
  const short = simulate({ ...seasonOne, casino: policy });
  const boxes = long.managers.flatMap((m) => m.boxesPerSeason);
  const checks = checkRanges(long);
  const pass = checks.filter((c) => c.gating).every((c) => c.withinRange);

  say(
    `| ${String(reserve)} tokens | **${percentile(boxes, 0.5).toFixed(1)}** | ${percentile(boxes, 0.1).toFixed(1)} | ` +
      `${percentile(boxes, 0.9).toFixed(1)} | ${percentile(short.managers.map((m) => m.owned), 0.5).toFixed(1)} / ${String(CATALOG_SIZE)} | ` +
      `**${pass ? 'PASS' : 'FAIL'}** |`,
  );
}
say();

/* ---------------------------------------------------------- the real lever -- */

const WEEKLY_INCOME =
  PROVISIONAL_ECONOMY.matchupWinTokens * 0.5 + PROVISIONAL_ECONOMY.weeklyHighScoreTokens * 0.1;

say('## 9. Wager size against weekly income — the lever that actually moves this');
say();
say(
  `A median manager earns **${WEEKLY_INCOME.toFixed(0)} tokens a week** ` +
    `(${String(PROVISIONAL_ECONOMY.matchupWinTokens)} × 50% of weeks + ${String(PROVISIONAL_ECONOMY.weeklyHighScoreTokens)} × 10%), ` +
    `which is ${(WEEKLY_INCOME * SCORED_WEEKS).toFixed(0)} a season and about ` +
    `${((WEEKLY_INCOME * SCORED_WEEKS) / PROVISIONAL_ECONOMY.standardBoxPriceTokens).toFixed(1)} boxes. ` +
    'Every result above follows from one ratio: what a week of play costs, against that.',
);
say();
say('| Buttons (slots / blackjack) | Cost per week: casual | regular | heavy | Heavy as share of income |');
say('|---|---|---|---|---|');

const slotsAnalysis = analyse(RECOMMENDED);
const bjLossPerUnit = -sampled.ev;

for (const [slotWager, bjWager] of [
  [RECOMMENDED.wagers[0] ?? 5, 20],
  [RECOMMENDED.wagers[1] ?? 10, 40],
  [RECOMMENDED.wagers[2] ?? 20, 80],
] as const) {
  const perPlay =
    SLOT_SHARE * (slotsAnalysis.expectedLossByWager.get(slotWager) ?? 0) +
    (1 - SLOT_SHARE) * bjLossPerUnit * bjWager;
  const heavyWeekly = perPlay * CADENCE.heavy;
  say(
    `| ${String(slotWager)} / ${String(bjWager)} | ${(perPlay * CADENCE.casual).toFixed(0)} | ` +
      `${(perPlay * CADENCE.regular).toFixed(0)} | ${heavyWeekly.toFixed(0)} | ` +
      `**${pct(heavyWeekly / WEEKLY_INCOME, 0)}** |`,
  );
}
say();
say(
  `At the ${String(SLOTS_WAGER)}-token slots button one box costs ` +
    `**${Math.round(PROVISIONAL_ECONOMY.standardBoxPriceTokens / (slotsAnalysis.expectedLossByWager.get(SLOTS_WAGER) ?? 1)).toLocaleString('en-US')} spins** of expected loss. ` +
    'That single number is the whole economy question: it is large enough that a casual player never notices ' +
    'and small enough that a determined one converts their collection into entertainment.',
);
say();
say('### The same league, at the lowest buttons');
say();

const lowPolicy: CasinoPolicy = {
  ...policyFor(defaultRoster(MANAGERS)),
  slots: slotsGame(RECOMMENDED, RECOMMENDED.wagers[0] ?? 5),
  blackjack: blackjackGame(sampled.outcomes, 20),
};

say('| Buttons | Archetype | Boxes in season 1 (median) | Unique items after season 1 |');
say('|---|---|---|---|');
for (const [label, slotWager, bjWager] of [
  ['5 / 20 (lowest)', RECOMMENDED.wagers[0] ?? 5, 20],
  ['10 / 40 (middle)', SLOTS_WAGER, BLACKJACK_WAGER],
] as const) {
  for (const archetype of ['regular', 'heavy'] as const) {
    const policy: CasinoPolicy = {
      ...policyFor(uniformRoster(MANAGERS, archetype)),
      slots: slotsGame(RECOMMENDED, slotWager),
      blackjack: blackjackGame(sampled.outcomes, bjWager),
    };
    const short = simulate({ ...seasonOne, casino: policy });
    say(
      `| ${label} | ${archetype} | **${percentile(short.managers.flatMap((m) => m.boxesPerSeason), 0.5).toFixed(1)}** | ` +
        `**${percentile(short.managers.map((m) => m.owned), 0.5).toFixed(1)}** / ${String(CATALOG_SIZE)} |`,
    );
  }
}
say();
const lowMixed = simulate({ ...base, casino: lowPolicy });
const lowChecks = checkRanges(lowMixed);
say(
  `Mixed league at the lowest buttons: median ${lowChecks.find((c) => c.name.startsWith('Boxes'))?.measured ?? '—'} boxes, ` +
    `gate **${lowChecks.filter((c) => c.gating).every((c) => c.withinRange) ? 'PASS' : 'FAIL'}**.`,
);
say();

const path = join(process.cwd(), 'docs/evidence/casino/analysis.md');
mkdirSync(dirname(path), { recursive: true });
writeFileSync(path, `${out.join('\n')}\n`);
console.log(`\nwritten → ${path}`);
