import Link from 'next/link';

import { BuyBox } from '@/components/counter/buy-box';
import { PanelHeading, PixelPanel, ReturnPlate, SignPlate } from '@/components/scene/panel';
import { RoomBehind } from '@/components/scene/room-behind';
import { Page } from '@/components/shell';
import { requireUser } from '@/lib/auth/current-user';
import { counterState } from '@/lib/counter/boxes';
import { economyFor, openSeason, wallet } from '@/lib/counter/tokens';
import { getDb } from '@/lib/db';

/**
 * Tony's Counter.
 *
 * **`/counter`, not `/shop`** — the product takes no money, and "the counter"
 * is what Tony calls it. `/counter/collection` and `/counter/showcase` sit
 * beneath this; `/counter/collection` ships here, `/counter/showcase` follows.
 *
 * ## Landing priority, from `18 §4`
 *
 * Owned unopened box → available stock → collection progress. There is no
 * *rotation* yet — that is league-wide, deterministic, generated by the Tuesday
 * job, and the job does not exist (`18 §4.2`) — so "available stock" is the one
 * standard box, at the one provisional price. Nothing here invents a countdown or
 * a second tier.
 *
 * ## The prices are provisional, and they live in the database
 *
 * `03 §11`: *"Exact costs and probabilities belong in database configuration, not
 * hardcoded frontend logic."* This page reads `economy_configs`, and every value
 * is flagged provisional until the P3 simulation (`16 §8`).
 *
 * ## Opening still happens at the tray
 *
 * Worth restating because it is easy to get backwards later: **an owned box opens
 * at the tray, in place** (`18 §4.1`). This route is for buying and browsing.
 * Routing here to *open* would insert a navigation step into the most exciting
 * moment in the product.
 */

export const dynamic = 'force-dynamic';

export default async function CounterPage() {
  const { user } = await requireUser();
  const db = getDb();

  const [{ unopenedBoxes, collectiblesOwned }, season] = await Promise.all([
    counterState(db, user.id),
    openSeason(db),
  ]);

  // A manager with no seat this season has no wallet, which is a real state —
  // a co-owner, or somebody who has not been seated yet. They can still open a
  // box they own; they simply cannot buy one.
  /*
   * The wallet, and the prices in force.
   *
   * `economyFor` throws when a season has no stored config, and that strictness is
   * right for a *service*: `18 §4.3` will not have the first purchase of a deploy
   * silently invent an economy. But a throw here reached the manager as
   * **"Application error: a server-side exception has occurred"** — a white screen
   * on the shop's own page, which is a far worse failure than the one it was
   * guarding against.
   *
   * So the page absorbs it and answers in-world (`05 §8.5`), while the underlying
   * error still goes to the server log for whoever broke the seed. Production runs
   * `migrate → seed → build`, so this is the partial-seed case rather than the
   * normal one — but "rare" is not "impossible", and the shop should never show a
   * stack-trace page to ten friends.
   */
  const purse = season === null ? null : await purseFor(db, user.id, season.id);

  return (
    <>
      <RoomBehind />

      <Page>
        <div className="mx-auto w-full max-w-[420px] px-4 pt-6 pb-10">
          <SignPlate>Tony&rsquo;s counter</SignPlate>

          <p className="mt-4 text-[17px] leading-[1.5] text-paper-mid/80">
            {unopenedBoxes > 0
              ? 'There is a box on the tray with your name on it. Open it out front — Tony likes to watch.'
              : 'Tony wipes the counter and waits. The tray is empty.'}
          </p>

          <div className="mt-6 space-y-4">
            {/*
              * On the tray first, per the landing priority. A manager who already
              * owns a box should be told to go and open it before being sold
              * another one.
              */}
            {unopenedBoxes > 0 && (
              <PixelPanel className="px-4 py-4">
                <PanelHeading>On the tray</PanelHeading>
                <p className="mt-1.5 text-[17px] leading-[1.5] text-ink-700">
                  {plural(unopenedBoxes, 'unopened box', 'unopened boxes')}. It opens out at the
                  tray, not in here.
                </p>
              </PixelPanel>
            )}

            <PixelPanel className="px-4 py-4">
              <PanelHeading>Standard pizza box</PanelHeading>
              <p className="mt-1.5 text-[17px] leading-[1.5] text-ink-700">
                Mostly the ordinary stuff off the shelves. Now and then something that
                shouldn&rsquo;t be in a pizza box at all.
              </p>

              {purse === null ? (
                <p className="mt-3 text-[17px] leading-[1.5] text-ink-700">
                  Tony hasn&rsquo;t put a price on it yet. Nothing to buy with today.
                </p>
              ) : (
                <BuyBox
                  price={purse.economy.values.standardBoxPriceTokens}
                  balance={purse.balance}
                />
              )}
            </PixelPanel>

            {/*
              * The shelf's summary, and the way through to it.
              *
              * This panel once said "nothing collected yet" unconditionally, which
              * became a false statement about a manager's own property the moment a
              * box could be opened. It now counts, and `/counter/collection` is
              * where the pieces actually are.
              */}
            <PixelPanel className="px-4 py-4">
              <PanelHeading>Your collection</PanelHeading>
              <p className="mt-1.5 text-[17px] leading-[1.5] text-ink-700">
                {collectiblesOwned > 0
                  ? `${plural(collectiblesOwned, 'collectible', 'collectibles')}, kept permanently, across every season.`
                  : 'Nothing collected yet. What you pull is yours permanently, across every season.'}
              </p>

              {/*
                * Through to the shelf.
                *
                * It is offered even when the shelf is empty: set progress is the
                * reason to go and look, and hiding the route until somebody has
                * pulled something would make the counter's own claim about
                * permanence unverifiable.
                */}
              <Link
                href="/counter/collection"
                className="mt-3 flex min-h-[44px] items-center font-display text-[11px] tracking-wide text-ink-700/85 uppercase underline decoration-ink-700/30 underline-offset-2 active:translate-y-px"
              >
                Look at the shelves
              </Link>
            </PixelPanel>
          </div>

          <div className="mt-8">
            <ReturnPlate />
          </div>
        </div>
      </Page>
    </>
  );
}

/**
 * The manager's balance and the prices, or null if either is unavailable.
 *
 * Null covers two genuinely different situations that the page answers the same
 * way — no seat this season, and no stored prices — because in both cases the
 * honest thing to say is "there is nothing to buy with right now". The log tells
 * the difference apart; the manager does not need to.
 */
async function purseFor(
  db: ReturnType<typeof getDb>,
  userId: string,
  seasonId: string,
): Promise<{ balance: number; economy: Awaited<ReturnType<typeof economyFor>> } | null> {
  const held = await wallet(db, { userId, seasonId });
  if (held === null) return null;

  try {
    return { balance: held.balance, economy: await economyFor(db, seasonId) };
  } catch (error: unknown) {
    // Loud in the log, quiet in the shop.
    console.error('[counter] no economy config for the open season', error);
    return null;
  }
}

/** "1 collectible" / "3 collectibles". Counting is a fact, so it is stated exactly. */
function plural(n: number, one: string, many: string): string {
  return `${String(n)} ${n === 1 ? one : many}`;
}
