import Link from 'next/link';

import { BuyBox } from '@/components/counter/buy-box';
import { Tab, type TabMovement } from '@/components/counter/tab';
import { PanelHeading, PixelPanel, ReturnPlate, SignPlate } from '@/components/scene/panel';
import { RoomBehind } from '@/components/scene/room-behind';
import { Page } from '@/components/shell';
import { TYPE } from '@/lib/design/type';
import { requireUser } from '@/lib/auth/current-user';
import { counterState } from '@/lib/counter/boxes';
import { economyFor, openSeason, recentTransactions, wallet } from '@/lib/counter/tokens';
import { getDb } from '@/lib/db';

/**
 * Tony's Counter.
 *
 * **`/counter`, not `/shop`** — the product takes no money, and "the counter"
 * is what Tony calls it. `/counter/collection` and `/counter/showcase` sit
 * beneath this; `/counter/collection` ships here, `/counter/showcase` follows.
 *
 * ## Landing priority, from `18 §4`
 *
 * Owned unopened box → available stock → collection progress. There is no
 * *rotation* yet — that is league-wide, deterministic, generated by the Tuesday
 * job, and the job does not exist (`18 §4.2`) — so "available stock" is the one
 * standard box, at the one provisional price. Nothing here invents a countdown or
 * a second tier.
 *
 * ## The prices are provisional, and they live in the database
 *
 * `03 §11`: *"Exact costs and probabilities belong in database configuration, not
 * hardcoded frontend logic."* This page reads `economy_configs`, and every value
 * is flagged provisional until the P3 simulation (`16 §8`).
 *
 * ## Opening still happens at the tray
 *
 * Worth restating because it is easy to get backwards later: **an owned box opens
 * at the tray, in place** (`18 §4.1`). This route is for buying and browsing.
 * Routing here to *open* would insert a navigation step into the most exciting
 * moment in the product.
 */

export const dynamic = 'force-dynamic';

export default async function CounterPage() {
  const { user } = await requireUser();
  const db = getDb();

  const [{ unopenedBoxes, collectiblesOwned }, season] = await Promise.all([
    counterState(db, user.id),
    openSeason(db),
  ]);

  // A manager with no seat this season has no wallet, which is a real state —
  // a co-owner, or somebody who has not been seated yet. They can still open a
  // box they own; they simply cannot buy one.
  /*
   * The wallet, and the prices in force.
   *
   * `economyFor` throws when a season has no stored config, and that strictness is
   * right for a *service*: `18 §4.3` will not have the first purchase of a deploy
   * silently invent an economy. But a throw here reached the manager as
   * **"Application error: a server-side exception has occurred"** — a white screen
   * on the shop's own page, which is a far worse failure than the one it was
   * guarding against.
   *
   * So the page absorbs it and answers in-world (`05 §8.5`), while the underlying
   * error still goes to the server log for whoever broke the seed. Production runs
   * `migrate → seed → build`, so this is the partial-seed case rather than the
   * normal one — but "rare" is not "impossible", and the shop should never show a
   * stack-trace page to ten friends.
   */
  const purse = season === null ? null : await purseFor(db, user.id, season.id);

  // Whether they hold a seat at all, as opposed to holding one with no stored
  // prices. `purseFor` collapses both to null on purpose — the *page* needs the
  // difference only to say the right sentence.
  const seated =
    season === null ? false : (await wallet(db, { userId: user.id, seasonId: season.id })) !== null;

  return (
    <>
      <RoomBehind />

      <Page>
        <div className="mx-auto w-full max-w-[420px] px-4 pt-6 pb-10">
          <SignPlate>Tony&rsquo;s counter</SignPlate>

          {/*
            * What is true when you walk up, in Tony's voice — including the
            * count, which used to be a panel of its own.
            *
            * *"There is a box on the tray with your name on it"* and a panel
            * headed ON THE TRAY reading *"1 unopened box"* are the same fact
            * rendered twice, three lines apart. The panel lost: a shopkeeper
            * tells you there is one waiting, he does not also hand you a card
            * about it.
            */}
          <p
            /*
             * The count, as a marker as well as a sentence.
             *
             * The visual driver has to know when a purchase has landed, and it
             * used to know by waiting for the words *"unopened box"* — which is
             * a test coupled to prose, and it broke the moment the prose
             * improved. A number in an attribute is a contract the copy can be
             * rewritten around, the same way `data-room-object` lets the room's
             * labels change without moving the object map.
             */
            data-unopened-boxes={String(unopenedBoxes)}
            className={`mt-4 ${TYPE.body} text-paper-mid/85`}
          >
            {unopenedBoxes === 0
              ? 'Tony wipes the counter and waits. The tray is empty.'
              : unopenedBoxes === 1
                ? 'There is a box on the tray with your name on it. Open it out front — Tony likes to watch.'
                : `There are ${String(unopenedBoxes)} boxes on the tray with your name on them. They open out front — Tony likes to watch.`}
          </p>

          {/*
            * **One panel, because one thing is for sale.**
            *
            * There were three, identical in tone, size and heading style, stacked
            * down the screen — which reads as a list of cards rather than as a
            * counter with something on it (`docs/VISUAL_DEBT.md` 3). The other
            * two were not carrying a panel's worth of weight: one repeated the
            * line above it, and one was a sentence and a link.
            *
            * A panel is for the thing you can *act on*. That is the box.
            *
            * The statement below is the **second** panel, and it is not a
            * relapse. The three that were removed repeated each other and the
            * sentences around them; a statement is the one thing on this page
            * the manager cannot get anywhere else, and `03 §5` requires the
            * displayed balance to be reconcilable to the ledger. It carries no
            * balance of its own for exactly the reason the paragraph above
            * gives — `BuyBox` already says it, three lines up.
            */}
          <div className="mt-6">
            <PixelPanel className="px-4 pt-4 pb-4">
              <PanelHeading>Standard pizza box</PanelHeading>
              <p className={`mt-1.5 ${TYPE.body} text-ink-700`}>
                Mostly the ordinary stuff off the shelves. Now and then something that
                shouldn&rsquo;t be in a pizza box at all.
              </p>

              {purse === null ? (
                /*
                 * Two genuinely different situations used to share this line,
                 * and one of them was told something untrue: a manager with no
                 * seat was shown *"Tony hasn't put a price on it yet"* when the
                 * price is set and it is the tab they do not have.
                 *
                 * A wrong reason is worse than a blunt one. So they are told
                 * apart now — the seatless case is a real, supported state and
                 * says what it is, and the no-config case keeps the vaguer line
                 * because it is a seeding failure nobody but an operator can act
                 * on (and it is still loud in the log).
                 */
                <p className={`mt-3 ${TYPE.body} text-ink-700`}>
                  {seated
                    ? 'Tony hasn’t put a price on it yet. Nothing to buy with today.'
                    : 'No seat this season, so no tab to run one up on. The shelf behind you is still yours.'}
                </p>
              ) : (
                <BuyBox
                  price={purse.economy.values.standardBoxPriceTokens}
                  balance={purse.balance}
                />
              )}
            </PixelPanel>
          </div>

          {/*
            * The way to the back, printed on the counter rather than boxed.
            *
            * A sentence and a link do not need a bevelled surface around them.
            * Sitting straight on the dimmed room they read as what they are —
            * the direction the shelves are in — instead of as a third product
            * card. Set on the room's own ink so it stays legible against the
            * parlor behind (`VISUAL_ACCEPTANCE.md §4`).
            *
            * Offered even when the shelf is empty: set progress is the reason to
            * go and look, and hiding the route until somebody has pulled
            * something would make the counter's claim about permanence
            * unverifiable.
            */}
          {/*
            * The statement, under the thing it pays for.
            *
            * Only when there is a tab to show one for — a manager with no seat
            * has no wallet, and an empty ledger addressed to them would be
            * answering a question they cannot ask.
            *
            * Deliberately *below* the box: the reason to come here is to buy
            * something, and a wall of accounting above the counter would make
            * the shop read as a bank statement.
            */}
          {purse !== null && (
            <div className="mt-6">
              <PixelPanel className="px-4 pt-4 pb-4">
                <PanelHeading>Your tab</PanelHeading>
                <div className="mt-2">
                  <Tab movements={purse.movements} />
                </div>
              </PixelPanel>
            </div>
          )}

          <div className="mt-7">
            <p className={`${TYPE.body} text-paper-mid/85`}>
              {collectiblesOwned > 0
                ? `${plural(collectiblesOwned, 'collectible', 'collectibles')} on your shelf, kept permanently, across every season.`
                : 'Nothing on your shelf yet. What you pull is yours permanently, across every season.'}
            </p>

            <Link
              href="/counter/collection"
              className={`mt-1 flex min-h-[44px] items-center ${TYPE.eyebrow} text-amber-glow underline decoration-amber-glow/40 underline-offset-4 active:translate-y-px`}
            >
              Look at the shelves
            </Link>
          </div>

          <div className="mt-8">
            <ReturnPlate />
          </div>
        </div>
      </Page>
    </>
  );
}

/**
 * The manager's balance and the prices, or null if either is unavailable.
 *
 * Null covers two genuinely different situations that the page answers the same
 * way — no seat this season, and no stored prices — because in both cases the
 * honest thing to say is "there is nothing to buy with right now". The log tells
 * the difference apart; the manager does not need to.
 */
async function purseFor(
  db: ReturnType<typeof getDb>,
  userId: string,
  seasonId: string,
): Promise<{
  balance: number;
  economy: Awaited<ReturnType<typeof economyFor>>;
  movements: readonly TabMovement[];
} | null> {
  const held = await wallet(db, { userId, seasonId });
  if (held === null) return null;

  try {
    return {
      balance: held.balance,
      economy: await economyFor(db, seasonId),
      /*
       * Six, because the statement sits under the thing a manager came here to
       * buy rather than being the page. A season's worth of Tuesdays belongs on
       * a surface built for it, and no such surface is in v1.
       */
      movements: await recentTransactions(db, held.membershipId, 6),
    };
  } catch (error: unknown) {
    // Loud in the log, quiet in the shop.
    console.error('[counter] no economy config for the open season', error);
    return null;
  }
}

/** "1 collectible" / "3 collectibles". Counting is a fact, so it is stated exactly. */
function plural(n: number, one: string, many: string): string {
  return `${String(n)} ${n === 1 ? one : many}`;
}
