import { BuyBox } from '@/components/counter/buy-box';
import { PanelHeading, PixelPanel, ReturnPlate, SignPlate } from '@/components/scene/panel';
import { RoomBehind } from '@/components/scene/room-behind';
import { Page } from '@/components/shell';
import { requireUser } from '@/lib/auth/current-user';
import { counterState } from '@/lib/counter/boxes';
import { economyFor, openSeason, wallet } from '@/lib/counter/tokens';
import { getDb } from '@/lib/db';

/**
 * Tony's Counter.
 *
 * **`/counter`, not `/shop`** — the product takes no money, and "the counter"
 * is what Tony calls it. `/counter/collection` and `/counter/showcase` sit
 * beneath this when they ship.
 *
 * ## Landing priority, from `18 §4`
 *
 * Owned unopened box → available stock → collection progress. There is no
 * *rotation* yet — that is league-wide, deterministic, generated by the Tuesday
 * job, and the job does not exist (`18 §4.2`) — so "available stock" is the one
 * standard box, at the one provisional price. Nothing here invents a countdown or
 * a second tier.
 *
 * ## The prices are provisional, and they live in the database
 *
 * `03 §11`: *"Exact costs and probabilities belong in database configuration, not
 * hardcoded frontend logic."* This page reads `economy_configs`, and every value
 * is flagged provisional until the P3 simulation (`16 §8`).
 *
 * ## Opening still happens at the tray
 *
 * Worth restating because it is easy to get backwards later: **an owned box opens
 * at the tray, in place** (`18 §4.1`). This route is for buying and browsing.
 * Routing here to *open* would insert a navigation step into the most exciting
 * moment in the product.
 */

export const dynamic = 'force-dynamic';

export default async function CounterPage() {
  const { user } = await requireUser();
  const db = getDb();

  const [{ unopenedBoxes, collectiblesOwned }, season] = await Promise.all([
    counterState(db, user.id),
    openSeason(db),
  ]);

  // A manager with no seat this season has no wallet, which is a real state —
  // a co-owner, or somebody who has not been seated yet. They can still open a
  // box they own; they simply cannot buy one.
  const purse =
    season === null
      ? null
      : await (async () => {
          const [held, economy] = await Promise.all([
            wallet(db, { userId: user.id, seasonId: season.id }),
            economyFor(db, season.id),
          ]);
          return held === null ? null : { balance: held.balance, economy };
        })();

  return (
    <>
      <RoomBehind />

      <Page>
        <div className="mx-auto w-full max-w-[420px] px-4 pt-6 pb-10">
          <SignPlate>Tony&rsquo;s counter</SignPlate>

          <p className="mt-4 text-[17px] leading-[1.5] text-paper-mid/80">
            {unopenedBoxes > 0
              ? 'There is a box on the tray with your name on it. Open it out front — Tony likes to watch.'
              : 'Tony wipes the counter and waits. The tray is empty.'}
          </p>

          <div className="mt-6 space-y-4">
            {/*
              * On the tray first, per the landing priority. A manager who already
              * owns a box should be told to go and open it before being sold
              * another one.
              */}
            {unopenedBoxes > 0 && (
              <PixelPanel className="px-4 py-4">
                <PanelHeading>On the tray</PanelHeading>
                <p className="mt-1.5 text-[17px] leading-[1.5] text-ink-700">
                  {plural(unopenedBoxes, 'unopened box', 'unopened boxes')}. It opens out at the
                  tray, not in here.
                </p>
              </PixelPanel>
            )}

            <PixelPanel className="px-4 py-4">
              <PanelHeading>Standard pizza box</PanelHeading>
              <p className="mt-1.5 text-[17px] leading-[1.5] text-ink-700">
                Mostly the ordinary stuff off the shelves. Now and then something that
                shouldn&rsquo;t be in a pizza box at all.
              </p>

              {purse === null ? (
                <p className="mt-3 text-[17px] leading-[1.5] text-ink-700">
                  You have no tab open this season, so there is nothing to buy with.
                </p>
              ) : (
                <BuyBox
                  price={purse.economy.values.standardBoxPriceTokens}
                  balance={purse.balance}
                />
              )}
            </PixelPanel>

            {/*
              * The collection view is `/counter/collection` and lands in its own
              * slice. What must be true *now* is the count: this panel said
              * "nothing collected yet" unconditionally, and the moment a box could
              * be opened that became a false statement about a manager's own
              * property.
              */}
            <PixelPanel className="px-4 py-4">
              <PanelHeading>Your collection</PanelHeading>
              <p className="mt-1.5 text-[17px] leading-[1.5] text-ink-700">
                {collectiblesOwned > 0
                  ? `${plural(collectiblesOwned, 'collectible', 'collectibles')}, kept permanently, across every season.`
                  : 'Nothing collected yet. What you pull is yours permanently, across every season.'}
              </p>
            </PixelPanel>
          </div>

          <div className="mt-8">
            <ReturnPlate />
          </div>
        </div>
      </Page>
    </>
  );
}

/** "1 collectible" / "3 collectibles". Counting is a fact, so it is stated exactly. */
function plural(n: number, one: string, many: string): string {
  return `${String(n)} ${n === 1 ? one : many}`;
}
